// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto
#ifndef GRPC_masterworker_2eproto__INCLUDED
#define GRPC_masterworker_2eproto__INCLUDED

#include "masterworker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace masterworker {

class MasterWorkerService final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.MasterWorkerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::masterworker::TaskResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>> AsyncExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>>(AsyncExecuteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>> PrepareAsyncExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>>(PrepareAsyncExecuteTaskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>* AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::TaskResult>* PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::masterworker::TaskResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>> AsyncExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>>(AsyncExecuteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>> PrepareAsyncExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>>(PrepareAsyncExecuteTaskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response, std::function<void(::grpc::Status)>) override;
      void ExecuteTask(::grpc::ClientContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>* AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::TaskResult>* PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::masterworker::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExecuteTask(::grpc::ServerContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTask(::grpc::ServerContext* context, ::masterworker::TaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::TaskResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteTask<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::masterworker::TaskRequest, ::masterworker::TaskResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::masterworker::TaskRequest* request, ::masterworker::TaskResult* response) { return this->ExecuteTask(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteTask(
        ::grpc::MessageAllocator< ::masterworker::TaskRequest, ::masterworker::TaskResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::masterworker::TaskRequest, ::masterworker::TaskResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExecuteTask<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::masterworker::TaskRequest, ::masterworker::TaskResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::masterworker::TaskRequest, ::masterworker::TaskResult>* streamer) {
                       return this->StreamedExecuteTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::masterworker::TaskRequest* /*request*/, ::masterworker::TaskResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::TaskRequest,::masterworker::TaskResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteTask<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecuteTask<Service > StreamedService;
};

}  // namespace masterworker


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_masterworker_2eproto__INCLUDED
